version: "3"

services:
  ventscript_php:
    image: php:8.1.18-fpm
    volumes:
      - "./src:/var/www/html"
      - "./docker/volumes/composer:/var/www/"
    networks:
      - titleSite

  ventscript_nginx:
    image: nginx:latest
    ports:
      - 8082:80
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - titleSite

networks:
  titleSite:
    external: true
    name: titleSite
    driver: bridge