version: "3"

services:
  ventscript_php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - "./src:/var/www/html"
      - "./docker/php/composer.json:/var/www/html/composer.json"
      - "./docker/php/composer.lock:/var/www/html/composer.lock"
      - ./docker/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

  ventscript_nginx:
    image: nginx:latest
    ports:
      - 8082:80
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - ventscript_php
    networks:
      - internal

networks:
  internal:
    driver: bridge
